import { UserCourse } from "@client/lib/types/course";
import { saveDocumentByEmail } from "../db/userPouchCRUD";
import { userDB, assignmentDB, courseDB } from "../db/pouchdbSetup";
import { DegreeRequirementAssignment } from "@client/lib/types/Degree";
import { saveAccount } from "../db/dbCRUD";

export const TEST_ACCOUNT_EMAIL = "bgreene@umass.edu";

async function addTestUserCourses() {
    const userCourses: UserCourse[] = [
        {
            course: {
                id: "COMPSCI|187",
                subjectId: "COMPSCI",
                number: "187",
                title: "Data Structures",
                titleLong: "Data Structures",
                displayTitle: "187 Data Structures",
                credits: "4",
            },
            semester: "Fall 2021",
            grade: "A",
            transferred: false,
        },
        {
            grade: "",
            notes: "",
            professor: "",
            semester: "Fall 2021",
            transferred: false,
            course: {
                id: "MATH|132",
                subjectLong: "Mathematics",
                subjectShort: "Mathematic",
                subjectId: "MATH",
                number: "132",
                topic: null,
                displayTitle: "132 Calculus II",
                title: "Calculus II",
                titleLong: "Mathematics 132 - Calculus II",
                description: null,
                hasTopics: false,
                corequisites: null,
                prerequisites: null,
                hasRestrictions: false,
                credits: "4",
            },
        },
        {
            grade: "",
            notes: "",
            professor: "",
            semester: "Fall 2021",
            transferred: false,
            course: {
                id: "COMPSCI|198C",
                subjectLong: "Computer Science",
                subjectShort: "CompSci",
                subjectId: "COMPSCI",
                number: "198C",
                topic: null,
                displayTitle: "198C P-Intro/C Programming Language",
                title: "P-Intro/C Programming Language",
                titleLong:
                    "Computer Science 198C - P-Intro/C Programming Language",
                description: null,
                hasTopics: false,
                corequisites: null,
                prerequisites: null,
                hasRestrictions: false,
                credits: "1",
            },
        },
        {
            grade: "",
            notes: "",
            professor: "",
            semester: "Fall 2021",
            transferred: false,
            course: {
                id: "ECON|103",
                subjectLong: "Economics",
                subjectShort: "Economics",
                subjectId: "ECON",
                number: "103",
                topic: null,
                displayTitle: "103 Introduction to Microeconomics",
                title: "Introduction to Microeconomics",
                titleLong: "Economics 103 - Introduction to Microeconomics",
                description: null,
                hasTopics: false,
                corequisites: null,
                prerequisites: null,
                hasRestrictions: false,
                credits: "4",
            },
        },
        {
            grade: "",
            notes: "",
            professor: "",
            semester: "Fall 2021",
            transferred: false,
            course: {
                id: "ENGLWRIT|112",
                subjectLong: "English Writing Program",
                subjectShort: "English Wr",
                subjectId: "ENGLWRIT",
                number: "112",
                topic: null,
                displayTitle: "112 College Writing",
                title: "College Writing",
                titleLong: "English Writing Program 112 - College Writing",
                description: null,
                hasTopics: false,
                corequisites: null,
                prerequisites: null,
                hasRestrictions: false,
                credits: "3",
            },
        },
        {
            grade: "",
            notes: "",
            professor: "",
            semester: "Fall 2021",
            transferred: false,
            course: {
                id: "CICS|191FY1",
                subjectLong: "College of Inform & Comp Sci",
                subjectShort: "InfoCompSc",
                subjectId: "CICS",
                number: "191FY1",
                topic: null,
                displayTitle: "191FY1 FYS - CICS First Year Seminar",
                title: "FYS - CICS First Year Seminar",
                titleLong:
                    "College of Inform & Comp Sci 191FY1 - FYS - CICS First Year Seminar",
                description: null,
                hasTopics: false,
                corequisites: null,
                prerequisites: null,
                hasRestrictions: false,
                credits: "1",
            },
        },
        {
            grade: "",
            notes: "",
            professor: "",
            semester: "Fall 2021",
            transferred: false,
            course: {
                id: "UNIVRSTY|191A",
                subjectLong: "Univ Interdepartmental Course",
                subjectShort: "Universty",
                subjectId: "UNIVRSTY",
                number: "191A",
                topic: null,
                displayTitle: "191A S-Power Up For College Success",
                title: "PART",
                titleLong:
                    "Univ Interdepartmental Course 191A - S-Power Up For College Success",
                description: null,
                hasTopics: false,
                corequisites: null,
                prerequisites: null,
                hasRestrictions: false,
                credits: "1",
            },
        },
        {
            grade: "",
            notes: "",
            professor: "",
            semester: "Spring 2022",
            transferred: false,
            course: {
                id: "COMPSCI|230",
                subjectLong: "Computer Science",
                subjectShort: "CompSci",
                subjectId: "COMPSCI",
                number: "230",
                topic: null,
                displayTitle: "230 Computer Systems Principles",
                title: "Computer Systems Principles",
                titleLong: "Computer Science 230 - Computer Systems Principles",
                description: null,
                hasTopics: false,
                corequisites: null,
                prerequisites: null,
                hasRestrictions: false,
                credits: "4",
            },
        },
        {
            grade: "",
            notes: "",
            professor: "",
            semester: "Spring 2022",
            transferred: false,
            course: {
                id: "COMPSCI|250",
                subjectLong: "Computer Science",
                subjectShort: "CompSci",
                subjectId: "COMPSCI",
                number: "250",
                topic: null,
                displayTitle: "250 Introduction To Computation",
                title: "Introduction To Computation",
                titleLong: "Computer Science 250 - Introduction To Computation",
                description: null,
                hasTopics: false,
                corequisites: null,
                prerequisites: null,
                hasRestrictions: false,
                credits: "4",
            },
        },
        {
            grade: "",
            notes: "",
            professor: "",
            semester: "Spring 2022",
            transferred: false,
            course: {
                id: "MATH|233",
                subjectLong: "Mathematics",
                subjectShort: "Mathematic",
                subjectId: "MATH",
                number: "233",
                topic: null,
                displayTitle: "233 Multivariate Calculus",
                title: "Multivariate Calculus",
                titleLong: "Mathematics 233 - Multivariate Calculus",
                description: null,
                hasTopics: false,
                corequisites: null,
                prerequisites: null,
                hasRestrictions: false,
                credits: "4",
            },
        },
        {
            grade: "",
            notes: "",
            professor: "",
            semester: "Spring 2022",
            transferred: false,
            course: {
                id: "MATH|235",
                subjectLong: "Mathematics",
                subjectShort: "Mathematic",
                subjectId: "MATH",
                number: "235",
                topic: null,
                displayTitle: "235 Intro Linear Algebra",
                title: "Intro Linear Algebra",
                titleLong: "Mathematics 235 - Intro Linear Algebra",
                description: null,
                hasTopics: false,
                corequisites: null,
                prerequisites: null,
                hasRestrictions: false,
                credits: "3",
            },
        },
        {
            grade: "",
            notes: "",
            professor: "",
            semester: "Spring 2022",
            transferred: false,
            course: {
                id: "PUBHLTH|160",
                subjectLong: "Public Health",
                subjectShort: "PublicHlth",
                subjectId: "PUBHLTH",
                number: "160",
                topic: null,
                displayTitle: "160 My Body, My Health",
                title: "My Body, My Health",
                titleLong: "Public Health 160 - My Body, My Health",
                description: null,
                hasTopics: false,
                corequisites: null,
                prerequisites: null,
                hasRestrictions: false,
                credits: "4",
            },
        },
        {
            grade: "",
            notes: "",
            professor: "",
            semester: "Fall 2022",
            transferred: false,
            course: {
                id: "COMPSCI|220",
                subjectLong: "Computer Science",
                subjectShort: "CompSci",
                subjectId: "COMPSCI",
                number: "220",
                topic: null,
                displayTitle: "220 Programming Methodology",
                title: "Programming Methodology",
                titleLong: "Computer Science 220 - Programming Methodology",
                description: null,
                hasTopics: false,
                corequisites: null,
                prerequisites: null,
                hasRestrictions: false,
                credits: "4",
            },
        },
        {
            grade: "",
            notes: "",
            professor: "",
            semester: "Fall 2022",
            transferred: false,
            course: {
                id: "COMPSCI|240",
                subjectLong: "Computer Science",
                subjectShort: "CompSci",
                subjectId: "COMPSCI",
                number: "240",
                topic: null,
                displayTitle: "240 Reasoning Under Uncertainty",
                title: "Reasoning Under Uncertainty",
                titleLong: "Computer Science 240 - Reasoning Under Uncertainty",
                description: null,
                hasTopics: false,
                corequisites: null,
                prerequisites: null,
                hasRestrictions: false,
                credits: "4",
            },
        },
        {
            grade: "",
            notes: "",
            professor: "",
            semester: "Fall 2022",
            transferred: false,
            course: {
                id: "COMPSCI|377",
                subjectLong: "Computer Science",
                subjectShort: "CompSci",
                subjectId: "COMPSCI",
                number: "377",
                topic: null,
                displayTitle: "377 Operating Systems",
                title: "Operating Systems",
                titleLong: "Computer Science 377 - Operating Systems",
                description: null,
                hasTopics: false,
                corequisites: null,
                prerequisites: null,
                hasRestrictions: false,
                credits: "4",
            },
        },
        {
            grade: "",
            notes: "",
            professor: "",
            semester: "Fall 2022",
            transferred: false,
            course: {
                id: "MUSIC|150",
                subjectLong: "Music",
                subjectShort: "Music",
                subjectId: "MUSIC",
                number: "150",
                topic: null,
                displayTitle: "150 Lively Arts",
                title: "Lively Arts",
                titleLong: "Music 150 - Lively Arts",
                description: null,
                hasTopics: false,
                corequisites: null,
                prerequisites: null,
                hasRestrictions: false,
                credits: "4",
            },
        },
        {
            grade: "",
            notes: "",
            professor: "",
            semester: "Fall 2022",
            transferred: false,
            course: {
                id: "CICS|298A",
                subjectLong: "College of Inform & Comp Sci",
                subjectShort: "InfoCompSc",
                subjectId: "CICS",
                number: "298A",
                topic: null,
                displayTitle: "298A P- Leadership Practicum",
                title: "P- Leadership Practicum",
                titleLong:
                    "College of Inform & Comp Sci 298A - P- Leadership Practicum",
                description: null,
                hasTopics: false,
                corequisites: null,
                prerequisites: null,
                hasRestrictions: false,
                credits: "1",
            },
        },
        {
            grade: "",
            notes: "",
            professor: "",
            semester: "Spring 2023",
            transferred: false,
            course: {
                id: "COMPSCI|311",
                subjectLong: "Computer Science",
                subjectShort: "CompSci",
                subjectId: "COMPSCI",
                number: "311",
                topic: null,
                displayTitle: "311 Introduction to Algorithms",
                title: "Introduction to Algorithms",
                titleLong: "Computer Science 311 - Introduction to Algorithms",
                description: null,
                hasTopics: false,
                corequisites: null,
                prerequisites: null,
                hasRestrictions: false,
                credits: "4",
            },
        },
        {
            grade: "",
            notes: "",
            professor: "",
            semester: "Spring 2023",
            transferred: false,
            course: {
                id: "COMPSCI|390R",
                subjectLong: "Computer Science",
                subjectShort: "CompSci",
                subjectId: "COMPSCI",
                number: "390R",
                topic: null,
                displayTitle:
                    "390R Reverse Engineering and Vulnerability Analysis",
                title: "Reverse Engineering and Vulnerability Analysis",
                titleLong:
                    "Computer Science 390R - Reverse Engineering and Vulnerability Analysis",
                description: null,
                hasTopics: false,
                corequisites: null,
                prerequisites: null,
                hasRestrictions: false,
                credits: "3",
            },
        },
        {
            grade: "",
            notes: "",
            professor: "",
            semester: "Spring 2023",
            transferred: false,
            course: {
                id: "STOCKSCH|171",
                subjectLong: "Stockbridge Sch of Agriculture",
                subjectShort: "StockSch",
                subjectId: "STOCKSCH",
                number: "171",
                topic: null,
                displayTitle: "171 Plagues, Food and People",
                title: "Plagues, Food and People",
                titleLong:
                    "Stockbridge Sch of Agriculture 171 - Plagues, Food and People",
                description: null,
                hasTopics: false,
                corequisites: null,
                prerequisites: null,
                hasRestrictions: false,
                credits: "4",
            },
        },
        {
            grade: "",
            notes: "",
            professor: "",
            semester: "Spring 2023",
            transferred: false,
            course: {
                id: "CICS|256",
                subjectLong: "College of Inform & Comp Sci",
                subjectShort: "InfoCompSc",
                subjectId: "CICS",
                number: "256",
                topic: null,
                displayTitle: "256 Make: Physical Computing",
                title: "Make: Physical Computing",
                titleLong:
                    "College of Inform & Comp Sci 256 - Make: Physical Computing",
                description: null,
                hasTopics: false,
                corequisites: null,
                prerequisites: null,
                hasRestrictions: false,
                credits: "4",
            },
        },
        {
            grade: "",
            notes: "",
            professor: "",
            semester: "Fall 2023",
            transferred: false,
            course: {
                id: "COMPSCI|365",
                subjectLong: "Computer Science",
                subjectShort: "CompSci",
                subjectId: "COMPSCI",
                number: "365",
                topic: null,
                displayTitle: "365 Digital Forensics",
                title: "Digital Forensics",
                titleLong: "Computer Science 363 - Digital Forensics",
                description: null,
                hasTopics: false,
                corequisites: null,
                prerequisites: null,
                hasRestrictions: false,
                credits: "3",
            },
        },
        {
            grade: "",
            notes: "",
            professor: "",
            semester: "Fall 2023",
            transferred: false,
            course: {
                id: "COMPSCI|453",
                subjectLong: "Computer Science",
                subjectShort: "CompSci",
                subjectId: "COMPSCI",
                number: "453",
                topic: null,
                displayTitle: "453 Computer Networks",
                title: "Computer Networks",
                titleLong: "Computer Science 453 - Computer Networks",
                description: null,
                hasTopics: false,
                corequisites: null,
                prerequisites: null,
                hasRestrictions: false,
                credits: "3",
            },
        },
        {
            grade: "",
            notes: "",
            professor: "",
            semester: "Fall 2023",
            transferred: false,
            course: {
                id: "COMPSCI|514",
                subjectLong: "Computer Science",
                subjectShort: "CompSci",
                subjectId: "COMPSCI",
                number: "514",
                topic: null,
                displayTitle: "514 Algorithms for Data Science",
                title: "Algorithms for Data Science",
                titleLong: "Computer Science 514 - Algorithms for Data Science",
                description: null,
                hasTopics: false,
                corequisites: null,
                prerequisites: null,
                hasRestrictions: false,
                credits: "3",
            },
        },
        {
            grade: "",
            notes: "",
            professor: "",
            semester: "Fall 2023",
            transferred: false,
            course: {
                id: "COMPSCI|578",
                subjectLong: "Computer Science",
                subjectShort: "CompSci",
                subjectId: "COMPSCI",
                number: "578",
                topic: null,
                displayTitle: "578 Distributed Computing and Systems",
                title: "Distributed Computing and Systems",
                titleLong:
                    "Computer Science 578 - Distributed Computing and Systems",
                description: null,
                hasTopics: false,
                corequisites: null,
                prerequisites: null,
                hasRestrictions: false,
                credits: "3",
            },
        },
        {
            grade: "",
            notes: "",
            professor: "",
            semester: "Fall 2023",
            transferred: false,
            course: {
                id: "PHYSICS|151",
                subjectLong: "Physics",
                subjectShort: "Physics",
                subjectId: "PHYSICS",
                number: "151",
                topic: null,
                displayTitle: "151 General Physics I",
                title: "General Physics I",
                titleLong: "Physics 151 - General Physics I",
                description: null,
                hasTopics: false,
                corequisites: null,
                prerequisites: null,
                hasRestrictions: false,
                credits: "4",
            },
        },
        {
            grade: "",
            notes: "",
            professor: "",
            semester: "Fall 2023",
            transferred: false,
            course: {
                id: "MARKETNG|301",
                subjectLong: "Marketing",
                subjectShort: "Marketng",
                subjectId: "MARKETNG",
                number: "301",
                topic: null,
                displayTitle: "301 Fundamentals Of Marketing",
                title: "Fundamentals Of Marketing",
                titleLong: "Marketing 301 - Fundamentals Of Marketing",
                description: null,
                hasTopics: false,
                corequisites: null,
                prerequisites: null,
                hasRestrictions: false,
                credits: "3",
            },
        },
        {
            grade: "",
            notes: "",
            professor: "",
            semester: "Winter 2024",
            transferred: false,
            course: {
                id: "COMPSCI|345",
                subjectLong: "Computer Science",
                subjectShort: "CompSci",
                subjectId: "COMPSCI",
                number: "345",
                topic: null,
                displayTitle: "345 Pract & Appl of Data Managemnt",
                title: "Pract & Appl of Data Managemnt",
                titleLong:
                    "Computer Science 345 - Pract & Appl of Data Managemnt",
                description: null,
                hasTopics: false,
                corequisites: null,
                prerequisites: null,
                hasRestrictions: false,
                credits: "3",
            },
        },
        {
            grade: "",
            notes: "",
            professor: "",
            semester: "Spring 2024",
            transferred: false,
            course: {
                id: "COMPSCI|326",
                subjectLong: "Computer Science",
                subjectShort: "CompSci",
                subjectId: "COMPSCI",
                number: "326",
                topic: null,
                displayTitle: "326 Web Programming",
                title: "Web Programming",
                titleLong: "Computer Science 326 - Web Programming",
                description: null,
                hasTopics: false,
                corequisites: null,
                prerequisites: null,
                hasRestrictions: false,
                credits: "4",
            },
        },
        {
            grade: "",
            notes: "",
            professor: "",
            semester: "Spring 2024",
            transferred: false,
            course: {
                id: "COMPSCI|348",
                subjectLong: "Computer Science",
                subjectShort: "CompSci",
                subjectId: "COMPSCI",
                number: "348",
                topic: null,
                displayTitle: "348 Principles of Data Science",
                title: "Principles of Data Science",
                titleLong: "Computer Science 348 - Principles of Data Science",
                description: null,
                hasTopics: false,
                corequisites: null,
                prerequisites: null,
                hasRestrictions: false,
                credits: "3",
            },
        },
        {
            grade: "",
            notes: "",
            professor: "",
            semester: "Spring 2024",
            transferred: false,
            course: {
                id: "COMPSCI|590AE",
                subjectLong: "Computer Science",
                subjectShort: "CompSci",
                subjectId: "COMPSCI",
                number: "590AE",
                topic: null,
                displayTitle: "590AE Mobile and Wireless Networks",
                title: "Mobile and Wireless Networks",
                titleLong:
                    "Computer Science 590AE - Mobile and Wireless Networks",
                description: null,
                hasTopics: false,
                corequisites: null,
                prerequisites: null,
                hasRestrictions: false,
                credits: "3",
            },
        },
        {
            grade: "",
            notes: "",
            professor: "",
            semester: "Spring 2024",
            transferred: false,
            course: {
                id: "COMPSCI|391M",
                subjectLong: "Computer Science",
                subjectShort: "CompSci",
                subjectId: "COMPSCI",
                number: "391M",
                topic: null,
                displayTitle: "391M Seminar - Make: Audio Circuit Analysis",
                title: "Seminar - Make: Audio Circuit Analysis",
                titleLong:
                    "Computer Science 391M - Seminar - Make: Audio Circuit Analysis",
                description: null,
                hasTopics: false,
                corequisites: null,
                prerequisites: null,
                hasRestrictions: false,
                credits: "1",
            },
        },
        {
            grade: "",
            notes: "",
            professor: "",
            semester: "Spring 2024",
            transferred: false,
            course: {
                id: "MANAGMNT|301",
                subjectLong: "Management",
                subjectShort: "Managmnt",
                subjectId: "MANAGMNT",
                number: "301",
                topic: null,
                displayTitle: "301 Principles of Management",
                title: "Principles of Management",
                titleLong: "Management 301 - Principles of Management",
                description: null,
                hasTopics: false,
                corequisites: null,
                prerequisites: null,
                hasRestrictions: false,
                credits: "3",
            },
        },
    ];
    return saveDocumentByEmail(
        TEST_ACCOUNT_EMAIL,
        "courses",
        userCourses,
        courseDB,
    );
}

async function addTestUserAssignments() {
    const userAssignments: DegreeRequirementAssignment[] = [
        {
            id: "c5b5943e-9fc1-7c20-9d5f-0d64fe18a140",
            userCourse: {
                grade: "",
                notes: "",
                professor: "",
                semester: "Fall 2021",
                transferred: false,
                course: {
                    id: "MATH|132",
                    subjectLong: "Mathematics",
                    subjectShort: "Mathematic",
                    subjectId: "MATH",
                    number: "132",
                    topic: null,
                    displayTitle: "132 Calculus II",
                    title: "Calculus II",
                    titleLong: "Mathematics 132 - Calculus II",
                    description: null,
                    hasTopics: false,
                    corequisites: null,
                    prerequisites: null,
                    hasRestrictions: false,
                    credits: "4",
                },
            },
            requirement: {
                requirementType: "fixed",
                course: {
                    id: "MATH|132",
                    subjectLong: "Mathematics",
                    subjectShort: "Mathematic",
                    subjectId: "MATH",
                    number: "132",
                    topic: null,
                    displayTitle: "132 Calculus II",
                    title: "Calculus II",
                    titleLong: "Mathematics 132 - Calculus II",
                    description: null,
                    hasTopics: false,
                    corequisites: null,
                    prerequisites: null,
                    hasRestrictions: false,
                    credits: "4",
                },
            },
            status: "completed",
        },
        {
            id: "a2e5422c-329f-ed3a-516f-bd7554b8244e",
            userCourse: {
                grade: "",
                notes: "",
                professor: "",
                semester: "Fall 2021",
                transferred: false,
                course: {
                    id: "ENGLWRIT|112",
                    subjectLong: "English Writing Program",
                    subjectShort: "English Wr",
                    subjectId: "ENGLWRIT",
                    number: "112",
                    topic: null,
                    displayTitle: "112 College Writing",
                    title: "College Writing",
                    titleLong: "English Writing Program 112 - College Writing",
                    description: null,
                    hasTopics: false,
                    corequisites: null,
                    prerequisites: null,
                    hasRestrictions: false,
                    credits: "3",
                },
            },
            requirement: {
                requirementType: "fixed",
                course: {
                    id: "ENGLWRIT|112",
                    subjectLong: "English Writing Program",
                    subjectShort: "English Wr",
                    subjectId: "ENGLWRIT",
                    number: "112",
                    topic: null,
                    displayTitle: "112 College Writing",
                    title: "College Writing",
                    titleLong: "English Writing Program 112 - College Writing",
                    description: null,
                    hasTopics: false,
                    corequisites: null,
                    prerequisites: null,
                    hasRestrictions: false,
                    credits: "3",
                },
            },
            status: "completed",
        },
        {
            id: "b05005ac-2272-dd72-0915-7566745e350d",
            userCourse: {
                grade: "",
                notes: "",
                professor: "",
                semester: "Spring 2022",
                transferred: false,
                course: {
                    id: "COMPSCI|230",
                    subjectLong: "Computer Science",
                    subjectShort: "CompSci",
                    subjectId: "COMPSCI",
                    number: "230",
                    topic: null,
                    displayTitle: "230 Computer Systems Principles",
                    title: "Computer Systems Principles",
                    titleLong:
                        "Computer Science 230 - Computer Systems Principles",
                    description: null,
                    hasTopics: false,
                    corequisites: null,
                    prerequisites: null,
                    hasRestrictions: false,
                    credits: "4",
                },
            },
            requirement: {
                requirementType: "fixed",
                course: {
                    id: "COMPSCI|230",
                    subjectLong: "Computer Science",
                    subjectShort: "CompSci",
                    subjectId: "COMPSCI",
                    number: "230",
                    topic: null,
                    displayTitle: "230 Computer Systems Principles",
                    title: "Computer Systems Principles",
                    titleLong:
                        "Computer Science 230 - Computer Systems Principles",
                    description: null,
                    hasTopics: false,
                    corequisites: null,
                    prerequisites: null,
                    hasRestrictions: false,
                    credits: "4",
                },
            },
            status: "completed",
        },
        {
            id: "dcf8139d-b3d7-3338-d39d-eab611d51d44",
            userCourse: {
                grade: "",
                notes: "",
                professor: "",
                semester: "Spring 2022",
                transferred: false,
                course: {
                    id: "COMPSCI|250",
                    subjectLong: "Computer Science",
                    subjectShort: "CompSci",
                    subjectId: "COMPSCI",
                    number: "250",
                    topic: null,
                    displayTitle: "250 Introduction To Computation",
                    title: "Introduction To Computation",
                    titleLong:
                        "Computer Science 250 - Introduction To Computation",
                    description: null,
                    hasTopics: false,
                    corequisites: null,
                    prerequisites: null,
                    hasRestrictions: false,
                    credits: "4",
                },
            },
            requirement: {
                requirementType: "fixed",
                course: {
                    id: "COMPSCI|250",
                    subjectLong: "Computer Science",
                    subjectShort: "CompSci",
                    subjectId: "COMPSCI",
                    number: "250",
                    topic: null,
                    displayTitle: "250 Introduction To Computation",
                    title: "Introduction To Computation",
                    titleLong:
                        "Computer Science 250 - Introduction To Computation",
                    description: null,
                    hasTopics: false,
                    corequisites: null,
                    prerequisites: null,
                    hasRestrictions: false,
                    credits: "4",
                },
            },
            status: "completed",
        },
        {
            id: "641e4ec3-f332-06fa-4708-17c4a1bf2aff",
            userCourse: {
                grade: "",
                notes: "",
                professor: "",
                semester: "Spring 2022",
                transferred: false,
                course: {
                    id: "MATH|233",
                    subjectLong: "Mathematics",
                    subjectShort: "Mathematic",
                    subjectId: "MATH",
                    number: "233",
                    topic: null,
                    displayTitle: "233 Multivariate Calculus",
                    title: "Multivariate Calculus",
                    titleLong: "Mathematics 233 - Multivariate Calculus",
                    description: null,
                    hasTopics: false,
                    corequisites: null,
                    prerequisites: null,
                    hasRestrictions: false,
                    credits: "4",
                },
            },
            requirement: {
                requirementType: "fixed",
                course: {
                    id: "MATH|233",
                    subjectLong: "Mathematics",
                    subjectShort: "Mathematic",
                    subjectId: "MATH",
                    number: "233",
                    topic: null,
                    displayTitle: "233 Multivariate Calculus",
                    title: "Multivariate Calculus",
                    titleLong: "Mathematics 233 - Multivariate Calculus",
                    description: null,
                    hasTopics: false,
                    corequisites: null,
                    prerequisites: null,
                    hasRestrictions: false,
                    credits: "4",
                },
            },
            status: "completed",
        },
        {
            id: "5d1d9fac-e28b-54d0-39d8-df7cbeffa6d9",
            userCourse: {
                grade: "",
                notes: "",
                professor: "",
                semester: "Spring 2022",
                transferred: false,
                course: {
                    id: "MATH|235",
                    subjectLong: "Mathematics",
                    subjectShort: "Mathematic",
                    subjectId: "MATH",
                    number: "235",
                    topic: null,
                    displayTitle: "235 Intro Linear Algebra",
                    title: "Intro Linear Algebra",
                    titleLong: "Mathematics 235 - Intro Linear Algebra",
                    description: null,
                    hasTopics: false,
                    corequisites: null,
                    prerequisites: null,
                    hasRestrictions: false,
                    credits: "3",
                },
            },
            requirement: {
                requirementType: "fixed",
                course: {
                    id: "MATH|235",
                    subjectLong: "Mathematics",
                    subjectShort: "Mathematic",
                    subjectId: "MATH",
                    number: "235",
                    topic: null,
                    displayTitle: "235 Intro Linear Algebra",
                    title: "Intro Linear Algebra",
                    titleLong: "Mathematics 235 - Intro Linear Algebra",
                    description: null,
                    hasTopics: false,
                    corequisites: null,
                    prerequisites: null,
                    hasRestrictions: false,
                    credits: "3",
                },
            },
            status: "completed",
        },
        {
            id: "4ce92617-788c-7044-b709-fa09670bcb05",
            userCourse: {
                grade: "",
                notes: "",
                professor: "",
                semester: "Fall 2022",
                transferred: false,
                course: {
                    id: "COMPSCI|220",
                    subjectLong: "Computer Science",
                    subjectShort: "CompSci",
                    subjectId: "COMPSCI",
                    number: "220",
                    topic: null,
                    displayTitle: "220 Programming Methodology",
                    title: "Programming Methodology",
                    titleLong: "Computer Science 220 - Programming Methodology",
                    description: null,
                    hasTopics: false,
                    corequisites: null,
                    prerequisites: null,
                    hasRestrictions: false,
                    credits: "4",
                },
            },
            requirement: {
                requirementType: "fixed",
                course: {
                    id: "COMPSCI|220",
                    subjectLong: "Computer Science",
                    subjectShort: "CompSci",
                    subjectId: "COMPSCI",
                    number: "220",
                    topic: null,
                    displayTitle: "220 Programming Methodology",
                    title: "Programming Methodology",
                    titleLong: "Computer Science 220 - Programming Methodology",
                    description: null,
                    hasTopics: false,
                    corequisites: null,
                    prerequisites: null,
                    hasRestrictions: false,
                    credits: "4",
                },
            },
            status: "completed",
        },
        {
            id: "2699e0cf-44ab-7d3b-673f-eaa2ab66ed8e",
            userCourse: {
                grade: "",
                notes: "",
                professor: "",
                semester: "Fall 2022",
                transferred: false,
                course: {
                    id: "COMPSCI|240",
                    subjectLong: "Computer Science",
                    subjectShort: "CompSci",
                    subjectId: "COMPSCI",
                    number: "240",
                    topic: null,
                    displayTitle: "240 Reasoning Under Uncertainty",
                    title: "Reasoning Under Uncertainty",
                    titleLong:
                        "Computer Science 240 - Reasoning Under Uncertainty",
                    description: null,
                    hasTopics: false,
                    corequisites: null,
                    prerequisites: null,
                    hasRestrictions: false,
                    credits: "4",
                },
            },
            requirement: {
                requirementType: "fixed",
                course: {
                    id: "COMPSCI|240",
                    subjectLong: "Computer Science",
                    subjectShort: "CompSci",
                    subjectId: "COMPSCI",
                    number: "240",
                    topic: null,
                    displayTitle: "240 Reasoning Under Uncertainty",
                    title: "Reasoning Under Uncertainty",
                    titleLong:
                        "Computer Science 240 - Reasoning Under Uncertainty",
                    description: null,
                    hasTopics: false,
                    corequisites: null,
                    prerequisites: null,
                    hasRestrictions: false,
                    credits: "4",
                },
            },
            status: "completed",
        },
        {
            id: "9e4e22d2-d4eb-a2f9-0cee-4d1870eecb24",
            userCourse: {
                grade: "",
                notes: "",
                professor: "",
                semester: "Spring 2023",
                transferred: false,
                course: {
                    id: "COMPSCI|311",
                    subjectLong: "Computer Science",
                    subjectShort: "CompSci",
                    subjectId: "COMPSCI",
                    number: "311",
                    topic: null,
                    displayTitle: "311 Introduction to Algorithms",
                    title: "Introduction to Algorithms",
                    titleLong:
                        "Computer Science 311 - Introduction to Algorithms",
                    description: null,
                    hasTopics: false,
                    corequisites: null,
                    prerequisites: null,
                    hasRestrictions: false,
                    credits: "4",
                },
            },
            requirement: {
                requirementType: "fixed",
                course: {
                    id: "COMPSCI|311",
                    subjectLong: "Computer Science",
                    subjectShort: "CompSci",
                    subjectId: "COMPSCI",
                    number: "311",
                    topic: null,
                    displayTitle: "311 Introduction to Algorithms",
                    title: "Introduction to Algorithms",
                    titleLong:
                        "Computer Science 311 - Introduction to Algorithms",
                    description: null,
                    hasTopics: false,
                    corequisites: null,
                    prerequisites: null,
                    hasRestrictions: false,
                    credits: "4",
                },
            },
            status: "completed",
        },
        {
            id: "333f7d55-b987-1cc0-367a-32116d44102a",
            requirement: {
                requirementType: "anonymous",
                requirementId: "R1-Basic Math Skills",
                designation: "R1",
                description: "Basic Math Skills",
            },
            userCourse: {
                semester: "Completed",
                course: {
                    id: "4485a2f5-0284-2ab5-cd58-c3334b110e76",
                    subjectId: "R1",
                    number: "",
                    title: "Basic Math Skills",
                    displayTitle: "Anonymous Requirement",
                    credits: "0",
                    description: "Basic Math Skills",
                },
                transferred: true,
                creditsAwarded: "0",
            },
            status: "completed",
        },
        {
            id: "2a2bc5c7-0a8a-d55f-d8a6-97300a101707",
            userCourse: {
                grade: "",
                notes: "",
                professor: "",
                semester: "Fall 2021",
                transferred: false,
                course: {
                    id: "COMPSCI|187",
                    subjectId: "COMPSCI",
                    number: "187",
                    title: "Data Structures",
                    titleLong: "Data Structures",
                    displayTitle: "187 Data Structures",
                    credits: "4",
                },
            },
            requirement: {
                requirementType: "fixed",
                course: {
                    id: "COMPSCI|187",
                    subjectId: "COMPSCI",
                    number: "187",
                    title: "Data Structures",
                    titleLong: "Data Structures",
                    displayTitle: "187 Data Structures",
                    credits: "4",
                },
            },
            status: "completed",
        },
        {
            id: "cef63624-502f-9bf5-589c-42e005cc8b94",
            requirement: {
                requirementType: "anonymous",
                requirementId: "R2-Analytical Reasoning",
                designation: "R2",
                description: "Analytical Reasoning",
            },
            userCourse: {
                semester: "Completed",
                course: {
                    id: "2a601a37-e00d-bdd1-77db-975e8a288b68",
                    subjectId: "R2",
                    number: "",
                    title: "Analytical Reasoning",
                    displayTitle: "Anonymous Requirement",
                    credits: "0",
                    description: "Analytical Reasoning",
                },
                transferred: true,
                creditsAwarded: "0",
            },
            status: "completed",
        },
        {
            id: "d01890c7-5ffb-24eb-c877-8e13efa59eda",
            requirement: {
                requirementType: "anonymous",
                requirementId: "BS-Biological Science",
                designation: "BS",
                description: "Biological Science",
            },
            userCourse: {
                grade: "",
                notes: "",
                professor: "",
                semester: "Spring 2023",
                transferred: false,
                course: {
                    id: "STOCKSCH|171",
                    subjectLong: "Stockbridge Sch of Agriculture",
                    subjectShort: "StockSch",
                    subjectId: "STOCKSCH",
                    number: "171",
                    topic: null,
                    displayTitle: "171 Plagues, Food and People",
                    title: "Plagues, Food and People",
                    titleLong:
                        "Stockbridge Sch of Agriculture 171 - Plagues, Food and People",
                    description: null,
                    hasTopics: false,
                    corequisites: null,
                    prerequisites: null,
                    hasRestrictions: false,
                    credits: "4",
                },
            },
            status: "completed",
        },
        {
            id: "fbc6bce3-f66e-8ae5-f1ae-9be369ff3a40",
            requirement: {
                requirementType: "anonymous",
                requirementId: "PS-Physical Science",
                designation: "PS",
                description: "Physical Science",
            },
            userCourse: {
                grade: "",
                notes: "",
                professor: "",
                semester: "Fall 2023",
                transferred: false,
                course: {
                    id: "PHYSICS|151",
                    subjectLong: "Physics",
                    subjectShort: "Physics",
                    subjectId: "PHYSICS",
                    number: "151",
                    topic: null,
                    displayTitle: "151 General Physics I",
                    title: "General Physics I",
                    titleLong: "Physics 151 - General Physics I",
                    description: null,
                    hasTopics: false,
                    corequisites: null,
                    prerequisites: null,
                    hasRestrictions: false,
                    credits: "4",
                },
            },
            status: "completed",
        },
        {
            id: "14874b14-f6d9-3141-5e27-0935c12a2d02",
            requirement: {
                requirementType: "anonymous",
                requirementId: "AL/AT",
                designation: "AL/AT",
                description: "Literature/Arts",
            },
            userCourse: {
                grade: "",
                notes: "",
                professor: "",
                semester: "Fall 2022",
                transferred: false,
                course: {
                    id: "MUSIC|150",
                    subjectLong: "Music",
                    subjectShort: "Music",
                    subjectId: "MUSIC",
                    number: "150",
                    topic: null,
                    displayTitle: "150 Lively Arts",
                    title: "Lively Arts",
                    titleLong: "Music 150 - Lively Arts",
                    description: null,
                    hasTopics: false,
                    corequisites: null,
                    prerequisites: null,
                    hasRestrictions: false,
                    credits: "4",
                },
            },
            status: "completed",
        },
        {
            id: "ad16bc97-e85b-e1b6-0c4d-2fe7e86c9f82",
            requirement: {
                requirementType: "anonymous",
                requirementId: "SB",
                designation: "SB",
                description: "Social and Behavioral Sciences",
            },
            userCourse: {
                grade: "",
                notes: "",
                professor: "",
                semester: "Fall 2021",
                transferred: false,
                course: {
                    id: "ECON|103",
                    subjectLong: "Economics",
                    subjectShort: "Economics",
                    subjectId: "ECON",
                    number: "103",
                    topic: null,
                    displayTitle: "103 Introduction to Microeconomics",
                    title: "Introduction to Microeconomics",
                    titleLong: "Economics 103 - Introduction to Microeconomics",
                    description: null,
                    hasTopics: false,
                    corequisites: null,
                    prerequisites: null,
                    hasRestrictions: false,
                    credits: "4",
                },
            },
            status: "completed",
        },
        {
            id: "96fe034c-55c9-081a-c160-5833c1cdab55",
            requirement: {
                requirementType: "anonymous",
                requirementId: "AL/AT/DB/I/SI",
                designation: "AL/AT/DB/I/SI",
                description: "Additional Social World or Interdisciplinary",
            },
            userCourse: {
                grade: "",
                notes: "",
                professor: "",
                semester: "Spring 2022",
                transferred: false,
                course: {
                    id: "PUBHLTH|160",
                    subjectLong: "Public Health",
                    subjectShort: "PublicHlth",
                    subjectId: "PUBHLTH",
                    number: "160",
                    topic: null,
                    displayTitle: "160 My Body, My Health",
                    title: "My Body, My Health",
                    titleLong: "Public Health 160 - My Body, My Health",
                    description: null,
                    hasTopics: false,
                    corequisites: null,
                    prerequisites: null,
                    hasRestrictions: false,
                    credits: "4",
                },
            },
            status: "completed",
        },
        {
            id: "386cd271-4e52-1c82-75ca-4ea03b47c410",
            requirement: {
                requirementType: "anonymous",
                requirementId: "IE-Integrative Experience-CS",
                designation: "IE CS320/326",
                description: "Integrative Experience (IE)",
            },
            userCourse: {
                grade: "",
                notes: "",
                professor: "",
                semester: "Spring 2024",
                transferred: false,
                course: {
                    id: "COMPSCI|326",
                    subjectLong: "Computer Science",
                    subjectShort: "CompSci",
                    subjectId: "COMPSCI",
                    number: "326",
                    topic: null,
                    displayTitle: "326 Web Programming",
                    title: "Web Programming",
                    titleLong: "Computer Science 326 - Web Programming",
                    description: null,
                    hasTopics: false,
                    corequisites: null,
                    prerequisites: null,
                    hasRestrictions: false,
                    credits: "4",
                },
            },
            status: "in-progress",
        },
        {
            id: "64a54876-c1b1-08c0-2527-a2b15970b5ca",
            requirement: {
                requirementType: "anonymous",
                requirementId: "CS-Lab Science-1",
                designation: "Lab Science",
                description: "An approved Lab Science course",
            },
            userCourse: {
                grade: "",
                notes: "",
                professor: "",
                semester: "Fall 2023",
                transferred: false,
                course: {
                    id: "PHYSICS|151",
                    subjectLong: "Physics",
                    subjectShort: "Physics",
                    subjectId: "PHYSICS",
                    number: "151",
                    topic: null,
                    displayTitle: "151 General Physics I",
                    title: "General Physics I",
                    titleLong: "Physics 151 - General Physics I",
                    description: null,
                    hasTopics: false,
                    corequisites: null,
                    prerequisites: null,
                    hasRestrictions: false,
                    credits: "4",
                },
            },
            status: "completed",
        },
        {
            id: "3b7b0820-14d4-32ef-be24-0ffde37c64e5",
            requirement: {
                requirementType: "anonymous",
                requirementId: "CS-Lab Science-2",
                designation: "Lab Science",
                description: "An approved Lab Science course",
            },
            userCourse: {
                grade: "",
                notes: "",
                professor: "",
                semester: "Spring 2023",
                transferred: false,
                course: {
                    id: "CICS|256",
                    subjectLong: "College of Inform & Comp Sci",
                    subjectShort: "InfoCompSc",
                    subjectId: "CICS",
                    number: "256",
                    topic: null,
                    displayTitle: "256 Make: Physical Computing",
                    title: "Make: Physical Computing",
                    titleLong:
                        "College of Inform & Comp Sci 256 - Make: Physical Computing",
                    description: null,
                    hasTopics: false,
                    corequisites: null,
                    prerequisites: null,
                    hasRestrictions: false,
                    credits: "4",
                },
            },
            status: "completed",
        },
        {
            id: "43eefbe8-0db8-14f4-f410-3189b8c6460b",
            requirement: {
                requirementType: "prefix",
                requirementId: "CS-300-1",
                subjectId: "COMPSCI",
                prefix: "300+",
                description: "",
            },
            userCourse: {
                grade: "",
                notes: "",
                professor: "",
                semester: "Fall 2022",
                transferred: false,
                course: {
                    id: "COMPSCI|377",
                    subjectLong: "Computer Science",
                    subjectShort: "CompSci",
                    subjectId: "COMPSCI",
                    number: "377",
                    topic: null,
                    displayTitle: "377 Operating Systems",
                    title: "Operating Systems",
                    titleLong: "Computer Science 377 - Operating Systems",
                    description: null,
                    hasTopics: false,
                    corequisites: null,
                    prerequisites: null,
                    hasRestrictions: false,
                    credits: "4",
                },
            },
            status: "completed",
        },
        {
            id: "51c9fcbb-cfe0-d7f7-5e82-f94a5a5810aa",
            requirement: {
                requirementType: "prefix",
                requirementId: "CS-300-2",
                subjectId: "COMPSCI",
                prefix: "300+",
                description: "",
            },
            userCourse: {
                grade: "",
                notes: "",
                professor: "",
                semester: "Winter 2024",
                transferred: false,
                course: {
                    id: "COMPSCI|345",
                    subjectLong: "Computer Science",
                    subjectShort: "CompSci",
                    subjectId: "COMPSCI",
                    number: "345",
                    topic: null,
                    displayTitle: "345 Pract & Appl of Data Managemnt",
                    title: "Pract & Appl of Data Managemnt",
                    titleLong:
                        "Computer Science 345 - Pract & Appl of Data Managemnt",
                    description: null,
                    hasTopics: false,
                    corequisites: null,
                    prerequisites: null,
                    hasRestrictions: false,
                    credits: "3",
                },
            },
            status: "completed",
        },
        {
            id: "650f1bd3-5f94-da23-e2ae-b31ac6c981fb",
            requirement: {
                requirementType: "prefix",
                requirementId: "CS-300-3",
                subjectId: "COMPSCI",
                prefix: "300+",
                description: "",
            },
            userCourse: {
                grade: "",
                notes: "",
                professor: "",
                semester: "Spring 2024",
                transferred: false,
                course: {
                    id: "COMPSCI|348",
                    subjectLong: "Computer Science",
                    subjectShort: "CompSci",
                    subjectId: "COMPSCI",
                    number: "348",
                    topic: null,
                    displayTitle: "348 Principles of Data Science",
                    title: "Principles of Data Science",
                    titleLong:
                        "Computer Science 348 - Principles of Data Science",
                    description: null,
                    hasTopics: false,
                    corequisites: null,
                    prerequisites: null,
                    hasRestrictions: false,
                    credits: "3",
                },
            },
            status: "in-progress",
        },
        {
            id: "a2057845-1c5a-2658-68d5-4807e9dc0352",
            requirement: {
                requirementType: "prefix",
                requirementId: "CS-400-2",
                subjectId: "COMPSCI",
                prefix: "400+",
                description: "",
            },
            userCourse: {
                grade: "",
                notes: "",
                professor: "",
                semester: "Fall 2023",
                transferred: false,
                course: {
                    id: "COMPSCI|453",
                    subjectLong: "Computer Science",
                    subjectShort: "CompSci",
                    subjectId: "COMPSCI",
                    number: "453",
                    topic: null,
                    displayTitle: "453 Computer Networks",
                    title: "Computer Networks",
                    titleLong: "Computer Science 453 - Computer Networks",
                    description: null,
                    hasTopics: false,
                    corequisites: null,
                    prerequisites: null,
                    hasRestrictions: false,
                    credits: "3",
                },
            },
            status: "completed",
        },
        {
            id: "2b8a4e14-a110-8db6-1055-d4a72774bc1e",
            requirement: {
                requirementType: "prefix",
                requirementId: "CS-400-3",
                subjectId: "COMPSCI",
                prefix: "400+",
                description: "",
            },
            userCourse: {
                grade: "",
                notes: "",
                professor: "",
                semester: "Fall 2023",
                transferred: false,
                course: {
                    id: "COMPSCI|514",
                    subjectLong: "Computer Science",
                    subjectShort: "CompSci",
                    subjectId: "COMPSCI",
                    number: "514",
                    topic: null,
                    displayTitle: "514 Algorithms for Data Science",
                    title: "Algorithms for Data Science",
                    titleLong:
                        "Computer Science 514 - Algorithms for Data Science",
                    description: null,
                    hasTopics: false,
                    corequisites: null,
                    prerequisites: null,
                    hasRestrictions: false,
                    credits: "3",
                },
            },
            status: "completed",
        },
    ];
    return saveDocumentByEmail(
        TEST_ACCOUNT_EMAIL,
        "userAssignments",
        userAssignments,
        assignmentDB,
    );
}

async function addAccountDetail() {
    return saveAccount({
        email: TEST_ACCOUNT_EMAIL,
        gradSem: "fall-2024",
        majors: ["computer-science-bs"],
    });
}

// async function addUserSelectedArrConfigs() {
//     const userSelectedArrConfigs: string[] = [];
//     return saveDocumentByEmail(
//         TEST_ACCOUNT_EMAIL,
//         "userSelectedArrConfigs",
//         userSelectedArrConfigs,
//         arr,
//     );
// }

export async function hydrateTestAccount(): Promise<void> {
    await addTestUserCourses();
    await addTestUserAssignments();
    await addAccountDetail();
    // await addUserSelectedArrConfigs();
}
