# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
# https://reflectoring.io/tutorial-cicd-github-actions-pm2-nodejs-aws-ec2/

name: Build

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted
    environment: Production

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"
      - name: Install
        run: npm install
      - name: Build
        working-directory: ./backend
        run: npm run build
      - name: lint
        working-directory: ./backend
        run: npm run lint
      - name: validate
        working-directory: ./backend
        run: npm run validate-prettiness
      - name: Install .env file
        working-directory: ./backend
        run: |
          touch .env
          echo GOOGLE_CLIENT_ID=${{ vars.GOOGLE_CLIENT_ID }} >> .env
          echo GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} >> .env
          echo SERVER_PORT=${{ vars.SERVER_PORT }} >> .env
          echo DATABASE_DIR=${{ vars.DATABASE_DIR }} >> .env
          cat .env
      - name: Deploy
        run: (cd frontend && npm run build); (cd backend && pm2 restart backendserver)
